export const GET_MY_BOOKINGS = 'GET_MY_BOOKINGS';
export const GET_MY_BOOKINGS_SUCCESS = 'GET_MY_BOOKINGS_SUCCESS';

export const UPDATE_MY_BOOKINGS = 'UPDATE_MY_BOOKINGS';
export const UPDATE_MY_BOOKINGS_SUCCESS = 'UPDATE_MY_BOOKINGS_SUCCESS';

export const BOOKINGS_ERROR = 'BOOKINGS_ERROR';
